name: Backend CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t backend-test ./backend

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Tag image
        run: docker tag backend-test ${{ secrets.DOCKER_USERNAME }}/backend-app:latest

      - name: Push image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/backend-app:latest

      - name: Run container
        run: docker run -d -p 5000:5000 --name backend-test backend-test

      - name: Wait for app
        run: sleep 5

      - name: Health check
        run: curl -f http://localhost:5000/health
